version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postify-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postify-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000" # S3 API Port
      - "9001:9001" # Web Console Port
    environment:
      MINIO_ROOT_USER: ${OBJECT_STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${OBJECT_STORAGE_PASSWORD}
    volumes:
      - minio-data:/data
    networks:
      - postify-network
    restart: unless-stopped
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: postify-nginx
    ports:
      - "80:80" # main
      - "443:443" # ssl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # ssl files
    networks:
      - postify-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - postify-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - postify-network
    restart: unless-stopped

  postify-app:
    build: .
    container_name: postify-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      OBJECT_STORAGE_ENDPOINT: http://minio:9000
      OBJECT_STORAGE_USER: ${OBJECT_STORAGE_USER}
      OBJECT_STORAGE_PASSWORD: ${OBJECT_STORAGE_PASSWORD}
      OBJECT_STORAGE_BUCKET: ${OBJECT_STORAGE_BUCKET}
      POSTIFY_SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      POSTIFY_SESSION_EXPIRATION: ${SESSION_EXPIRATION}
      POSTIFY_SESSION_REFRESH_EXPIRATION: ${SESSION_REFRESH_EXPIRATION}
      POSTIFY_SESSION_EXPIRED_DELETING_DELAY: ${SESSION_EXPIRED_DELETING_DELAY}
      POSTIFY_SESSION_EXPIRED_DELETING_COUNT: ${SESSION_EXPIRED_DELETING_COUNT}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - postify-network
    restart: unless-stopped

volumes:
  postgres-data:
  minio-data:
  grafana-storage:

networks:
  postify-network:
    driver: bridge