spring:
  application:
    name: Postify

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jackson:
    default-property-inclusion: non_null
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postify
    username: postify_user
    password: postify_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      pool-name: PostifyHikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

logging:
  level:
    root: INFO
    ru.jadegg2568.Postify: DEBUG

postify:
  session:
    secretKey: yEk<Cjzh%oAwAR9y0:&Uq|AmS$F|A*yw
    expiration: 1h
    refreshExpiration: 30d
    expiredDeleting:
      delay: 5m
      count: 10000