server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: Postify

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jackson:
    default-property-inclusion: non_null
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postify
    username: postify_user
    password: postify_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      pool-name: PostifyHikariPool
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway: # migrations
    enabled: true
    connect-retries: 5
    connect-retries-interval: 5s

logging:
  level:
    root: INFO
    ru.jadegg2568.Postify: DEBUG

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: postify-files

app:
  session:
    secretKey: yEk<Cjzh%oAwAR9y0:&Uq|AmS$F|A*yw
    accessExpiration: 1h
    refreshExpiration: 30d
    cleanup:
      expiration: 1h
      delay: 5m
      size: 10000
  views:
    cleanup:
      expiration: 24h
      delay: 1h
      size: 10000