server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: Postify

  devtools:
    restart:
      enabled: true

  jackson:
    default-property-inclusion: non_null

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAX_POOL:10}
      pool-name: PostifyHikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}

logging:
  level:
    root: ${SPRING_LOGGING_LEVEL_ROOT:INFO}
    ru.jadegg2568.Postify: ${SPRING_LOGGING_LEVEL_APP:DEBUG}

postify:
  session:
    secretKey: ${POSTIFY_SESSION_SECRET_KEY}

    expiration: ${POSTIFY_SESSION_EXPIRATION:1h}
    refreshExpiration: ${POSTIFY_SESSION_REFRESH_EXPIRATION:30d}

    expiredDeleting:
      delay: ${POSTIFY_SESSION_EXPIRED_DELETING_DELAY:5m}
      count: ${POSTIFY_SESSION_EXPIRED_DELETING_COUNT:10000}