package ru.jadegg2568.Postify.event;

public enum EventType {
    USER_REGISTERED,
    USER_LOGGED,
    USER_DELETED,
    USER_SESSION_REVOKED,
    USER_SESSIONS_REVOKED,

    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_VIEWED,
    POST_LIKED,
    POST_UNLIKED,

    DIALOGUE_CREATED,
    DIALOGUE_MESSAGE_SENT,

    FILE_UPLOADED,

    ADMIN_CHANGED_PERMISSIONS,
}
